<a href="https://colab.research.google.com/github/AronAhn/tf_udemy/blob/master/TF_basic_syntax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

!pip install tensorflow-gpu==2.0.0-rc1
import tensorflow as tf


     |████████████████████████████████| 380.5MB 42kB/s 
     |████████████████████████████████| 4.3MB 50.0MB/s 
     |████████████████████████████████| 501kB 64.2MB/s 


In [2]:
print(tf.__version__)

2.0.0-rc1


In [4]:
hello = tf.constant("Hello ")
world = tf.constant("World")
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.compat.v1.Session() as sess:
  result = sess.run(hello+world)

In [7]:
print(result)

b'Hello World'


In [0]:
a = tf.constant(10)
b = tf.constant(20)

In [9]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [0]:
with tf.compat.v1.Session() as sess:
  result = sess.run(a+b)

In [12]:
result

30

In [0]:
const = tf.constant(10)
fill_mat = tf.fill((4,4), 10)

In [0]:
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))

In [0]:
myrandn = tf.random.normal((4,4), mean=0, stddev=1.0)
myrandu = tf.random.uniform((4,4), minval=0, maxval=1)

In [0]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [0]:
# with tf.compat.v1.Session() as sess:
sess = tf.compat.v1.InteractiveSession()

In [18]:
for op in my_ops:
  print(sess.run(op))
  # print(op.eval() )

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-0.15078758 -1.8348222  -0.0161125   2.8016765 ]
 [-0.79497033  2.3651552   1.0434813  -1.4830849 ]
 [-0.7446665   2.0913823   0.02367937 -0.20632519]
 [ 1.3154837   0.19832695 -0.2811759  -0.09441722]]
[[0.9726914  0.89460814 0.99165094 0.04461896]
 [0.41842067 0.25039232 0.72652423 0.8034228 ]
 [0.9636766  0.8832544  0.82953286 0.62496114]
 [0.44969308 0.5388658  0.38426006 0.9923295 ]]


In [0]:
a = tf.constant([ [1,2],
                 [3,4]])

In [20]:
a.get_shape()

TensorShape([2, 2])

In [21]:
b = tf.constant([ [10], [100]])
b.get_shape()

TensorShape([2, 1])

In [0]:
result = tf.matmul(a, b)

In [23]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

### TF graphs

In [0]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [25]:
with tf.compat.v1.Session() as sess:
  result = sess.run(n3)
print(result)

3


In [26]:
print(n3)

Tensor("add_4:0", shape=(), dtype=int32)


In [27]:
print(tf.compat.v1.get_default_graph())

In [0]:
g = tf.Graph()

In [29]:
print(g)

In [30]:
graph_one = tf.compat.v1.get_default_graph()
print(graph_one)

In [31]:
graph_two = tf.Graph()
print(graph_two)

In [32]:
with graph_two.as_default():
  print(graph_two is tf.compat.v1.get_default_graph())

True


### Variables and placeholders

In [0]:
sess.close()

In [38]:
sess = tf.compat.v1.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py:1750: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [40]:
my_tensor = tf.random.uniform((4,4), 0, 1)
my_var = tf.Variable(initial_value = my_tensor)
print(my_var)

<tf.Variable 'Variable_1:0' shape=(4, 4) dtype=float32>


In [0]:
init = tf.compat.v1.global_variables_initializer()

In [0]:
sess.run(init)

In [45]:
sess.run(my_var)

array([[0.8841797 , 0.37093198, 0.38178813, 0.9110187 ],
       [0.3187219 , 0.18711245, 0.77924633, 0.10197365],
       [0.39660275, 0.83652043, 0.92230415, 0.6029805 ],
       [0.62908626, 0.04106772, 0.8638605 , 0.99986553]], dtype=float32)

In [0]:
ph = tf.compat.v1.placeholder(tf.float32, shape=(None, 5))